/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.StudentManager;
import Model.MonHoc;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BOT
 */
public class XemDiemThiSv extends javax.swing.JFrame {

    /**
     * Creates new form XemDiemThi
     */
    
    public List<MonHoc> list = new ArrayList<MonHoc>();
    
    public class Model extends DefaultTableModel{

        @Override
        public boolean isCellEditable(int row, int column) {
            return false; //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public int getColumnCount() {
            return 3; //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public int getRowCount() {
            return XemDiemThiSv.this.list.size(); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public Object getValueAt(int row, int column) {
            switch(column){
                case 0:
                    return list.get(row).getMaMonHoc();

                case 1:
                    return list.get(row).getTenMonHoc();

                case 2:
                    return list.get(row).getDiemThi();
                default:
                    return "";
            }
        }

        @Override
        public String getColumnName(int column) {
            switch(column){
                case 0:
                    return "Mã Môn Học";
                case 1:
                    return "Tên Môn Học";
                case 2:
                    return "Điểm";
                default:
                    return "";
            }
        }
        
        
        
    }
    
    
    public String maSv;
    public XemDiemThiSv() {
        initComponents();
//        load(this.maSv);
    }
    
    public void load(String maSv){
        try {
            StudentManager sm = new StudentManager();
            this.maSv = maSv;

            String name = sm.getDetail(maSv).getName();
            this.lbName.setText(name);
            this.lbMaSv.setText(maSv);
            this.list = sm.getListDiem(maSv);

            if(this.list.size() < 1){
                lbMessage.setText("Sinh Viên Không Có Điểm");
            } else {
                XemDiemThiSv.Model m = new XemDiemThiSv.Model();
                this.tbListDiem.setModel(m);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(XemDiemThiSv.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(XemDiemThiSv.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbListDiem = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbHoTen = new javax.swing.JLabel();
        pppppppppp = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbMaSv = new javax.swing.JLabel();
        lbMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbListDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Môn Học", "Tên Môn Học", "Điểm"
            }
        ));
        jScrollPane1.setViewportView(tbListDiem);

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 0, 0));
        btnBack.setText("Quay Lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("KẾT QUẢ THI");

        lbHoTen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbHoTen.setText("Họ Và Tên");

        pppppppppp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pppppppppp.setText("Mã Sinh Viên");

        lbName.setText("?");

        lbMaSv.setText("?");

        lbMessage.setForeground(new java.awt.Color(255, 0, 0));
        lbMessage.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbHoTen)
                            .addComponent(pppppppppp)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(233, 233, 233)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbMaSv, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHoTen)
                    .addComponent(lbName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pppppppppp)
                    .addComponent(lbMaSv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMessage)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ChiTietSinhVien sv = new ChiTietSinhVien();
        sv.loadDetail(this.maSv);
        sv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbMaSv;
    private javax.swing.JLabel lbMessage;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel pppppppppp;
    private javax.swing.JTable tbListDiem;
    // End of variables declaration//GEN-END:variables
}
